### ISSUE TITLE
Incorrect names in the sticker menu

### ISSUE THREAD

**Issue by z1ntex** [ESK0/eItems#1]
The menu items in which Community Sticker Capsule 1 , Sticker Capsule 2 , Sticker Capsule are stickers from Majors, and the stickers that should be in these capsules are missing.

**Comment by ESK0** [comment]
Please provide an example.

**Comment by z1ntex** [comment]
> Please provide an example.

Here's an example.There should be stickers from this capsule Community Sticker Capsule 1, which are not there.Instead of them there are majors stickers 
![1C2_irobXXo_cut-photo ru](https://user-images.githubusercontent.com/75583333/141061732-20dcd336-54c0-4cef-b55a-8811cdf7af00.jpg)

**Comment by ESK0** [comment]
Hi,

I translated few messages on HlMod, can you please tell me an example of missing stickers?

**Comment by z1ntex** [comment]
> Привет,
> 
> Я перевел несколько сообщений на HlMod, не могли бы вы, пожалуйста, привести мне пример отсутствующих наклеек?

Everything seems to be in place now. The stickers from these capsules are mixed in with the major stickers. They are in different places in the capsule.

![02KJsAJI1zw_cut-photo ru](https://user-images.githubusercontent.com/75583333/141254602-5bc78804-7397-4595-8cf5-be33d0b4f64f.jpg)

**Comment by ESK0** [comment]
Even this sticker is available? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866

I hope we fix mixed major stickers as soon as possible. This fix will not require a plugin update, only plugin reload or server restart.

**Comment by z1ntex** [comment]
> Even this sticker is available? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866
> 
> I hope we fix mixed major stickers as soon as possible. This fix will not require a plugin update, only plugin reload or server restart.

Yes.They are all there.Only mixed with stickers of majors

**Comment by z1ntex** [comment]
> Even this sticker is available? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866
> 
> I hope we fix mixed major stickers as soon as possible. This fix will not require a plugin update, only plugin reload or server restart.

I  want to ask.After so many updates, was there a fix missing the display of slots and map?Since recently a person said that he has it

**Comment by ESK0** [comment]
> > Even this sticker is available? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866
> > I hope we fix mixed major stickers as soon as possible. This fix will not require a plugin update, only plugin reload or server restart.
> 
> I want to ask.After so many updates, was there a fix missing the display of slots and map?Since recently a person said that he has it

It is an issue with changing a `sv_hibernate_when_empty` value by a plugin. I have added a `ForceDisableHibernation` value to the config file in the latest version https://github.com/ESK0/eItems/commit/8bd0c5531190d350281a137e2f0c0c9d6f6f351a. Having `ForceDisableHibernation` set to false will not parse eItems data immediately after server start but after first player connection (server waking up from hibernation), therefore map and slots should not be missing anymore

> > Even this sticker is available? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866
> > I hope we fix mixed major stickers as soon as possible. This fix will not require a plugin update, only plugin reload or server restart.
> 
> Yes.They are all there.Only mixed with stickers of majors

Great, we will debug and fix parser issue as soon as possible.

**Comment by z1ntex** [comment]
> > > Даже эта наклейка доступна? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866 Я надеюсь, что мы исправим смешанные основные наклейки как можно скорее. Это исправление не потребует обновления плагина, только перезагрузки плагина или перезагрузки сервера.
> > 
> > 
> > Я хочу спросить.После стольких обновлений было ли исправлено отсутствие отображения слотов и карты?С недавнего времени человек сказал, что у него это есть
> 
> Это проблема с изменением `sv_hibernate_when_empty` значение с помощью плагина. Я добавил `ForceDisableHibernation` значение файла конфигурации в последней версии [8bd0c55](https://github.com/ESK0/eItems/commit/8bd0c5531190d350281a137e2f0c0c9d6f6f351a). `ForceDisableHibernation`Значение false не будет анализировать данные eItems сразу после запуска сервера, но после первого подключения игрока (сервер выходит из спящего режима), поэтому карта и слоты больше не должны отсутствовать
> 
> > > Даже эта наклейка доступна? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866 Я надеюсь, что мы исправим смешанные основные наклейки как можно скорее. Это исправление не потребует обновления плагина, только перезагрузки плагина или перезагрузки сервера.
> > 
> > 
> > ДА.Они все там есть.Только вперемешку с наклейками специальностей
> 
> Отлично, мы отладим и исправим проблему с синтаксическим анализатором как можно скорее.

Thanks.We'll be waiting.

**Comment by z1ntex** [comment]
> > > Even this sticker is available? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866
> > > I hope we fix mixed major stickers as soon as possible. This fix will not require a plugin update, only plugin reload or server restart.
> > 
> > 
> > I want to ask.After so many updates, was there a fix missing the display of slots and map?Since recently a person said that he has it
> 
> It is an issue with changing a `sv_hibernate_when_empty` value by a plugin. I have added a `ForceDisableHibernation` value to the config file in the latest version [8bd0c55](https://github.com/ESK0/eItems/commit/8bd0c5531190d350281a137e2f0c0c9d6f6f351a). Having `ForceDisableHibernation` set to false will not parse eItems data immediately after server start but after first player connection (server waking up from hibernation), therefore map and slots should not be missing anymore
> 
> > > Even this sticker is available? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866
> > > I hope we fix mixed major stickers as soon as possible. This fix will not require a plugin update, only plugin reload or server restart.
> > 
> > 
> > Yes.They are all there.Only mixed with stickers of majors
> 
> Great, we will debug and fix parser issue as soon as possible.

One more request. Can you add patches to the sticker categories?

**Comment by ESK0** [comment]
> > > > Even this sticker is available? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866
> > > > I hope we fix mixed major stickers as soon as possible. This fix will not require a plugin update, only plugin reload or server restart.
> > > 
> > > 
> > > I want to ask.After so many updates, was there a fix missing the display of slots and map?Since recently a person said that he has it
> > 
> > 
> > It is an issue with changing a `sv_hibernate_when_empty` value by a plugin. I have added a `ForceDisableHibernation` value to the config file in the latest version [8bd0c55](https://github.com/ESK0/eItems/commit/8bd0c5531190d350281a137e2f0c0c9d6f6f351a). Having `ForceDisableHibernation` set to false will not parse eItems data immediately after server start but after first player connection (server waking up from hibernation), therefore map and slots should not be missing anymore
> > > > Even this sticker is available? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866
> > > > I hope we fix mixed major stickers as soon as possible. This fix will not require a plugin update, only plugin reload or server restart.
> > > 
> > > 
> > > Yes.They are all there.Only mixed with stickers of majors
> > 
> > 
> > Great, we will debug and fix parser issue as soon as possible.
> 
> One more request. Can you add patches to the sticker categories?

No, patches are not stickers even tho you can apply them as a weapon sticker. Look at my sticker how I implemented patches.

**Comment by z1ntex** [comment]
> > > > > Even this sticker is available? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866
> > > > > I hope we fix mixed major stickers as soon as possible. This fix will not require a plugin update, only plugin reload or server restart.
> > > > 
> > > > 
> > > > I want to ask.After so many updates, was there a fix missing the display of slots and map?Since recently a person said that he has it
> > > 
> > > 
> > > It is an issue with changing a `sv_hibernate_when_empty` value by a plugin. I have added a `ForceDisableHibernation` value to the config file in the latest version [8bd0c55](https://github.com/ESK0/eItems/commit/8bd0c5531190d350281a137e2f0c0c9d6f6f351a). Having `ForceDisableHibernation` set to false will not parse eItems data immediately after server start but after first player connection (server waking up from hibernation), therefore map and slots should not be missing anymore
> > > > > Even this sticker is available? https://hlmod.ru/threads/weapon-stickers.54767/page-46#post-551866
> > > > > I hope we fix mixed major stickers as soon as possible. This fix will not require a plugin update, only plugin reload or server restart.
> > > > 
> > > > 
> > > > Yes.They are all there.Only mixed with stickers of majors
> > > 
> > > 
> > > Great, we will debug and fix parser issue as soon as possible.
> > 
> > 
> > One more request. Can you add patches to the sticker categories?
> 
> No, patches are not stickers even tho you can apply them as a weapon sticker. Look at my sticker how I implemented patches.

One more question.Earlier, a bug was discovered that tickrate server drops to 16.Was it also corrected?

**Comment by ESK0** [comment]
eItems does not manipulate with tickrate in any way.. I don't have any tickrate issues personaly.

**Comment by z1ntex** [comment]
As it turned out, the sticker "Sticker health (holo)" is missing

**Comment by ESK0** [comment]
> 

Holo version of this sticker does not exists. Only gold. You can use https://csgostash.com/ to check.
