### ISSUE TITLE
He can get the Coins / Pins from CSGO

### ISSUE THREAD

**Issue by crashzk** [ESK0/eItems#1]
From what I understand of CSGOItems, it in this case is used with some plugins to automatically update Skins Weapons, Music Kit automatically when CSGO launches something, of course it would do the same thing, correct?

My question would be, if both your `eItems` could do this and also be able to get all the codes for the Coins / Pins items, would it be possible?

I ask because I would like to use with this plugin: https://github.com/rogeraabbccdd/Fake-Competitive-Rank-and-Coins

So he would be updating the Coins / Pins by himself.

**Comment by ESK0** [comment]
Yes, I plan to add support for Coins and Pins.

**Comment by crashzk** [comment]
Perfect, I will be waiting to test with some plugins of mine, thanks.

**Comment by ESK0** [comment]
Right now, I want to test 100% currently implemented functions before adding new ones.
