### ISSUE TITLE
Natives to get gloves paint?

### ISSUE THREAD

**Issue by samyycX** [ESK0/eItems#10]
Is there any native method to get glove paints?
i saw the `g_smGlovePaints` and `g_smGloveInfo` in the code,
so maybe there can be a native method to get glove paints by glovesNum or defIndex?

Or there is already a native method like this, and i didn't see it?

**Comment by samyycX** [comment]
it also looks like the weapons do not have a method to get all paints by weapon id too.

**Comment by crashzk** [comment]
@samyycX verified PR: https://github.com/ESK0/eItems/pull/12
