### ISSUE TITLE
Rename the files folder to eitems from the scripting folder

### ISSUE THREAD

**Issue by crashzk** [ESK0/eItems#2]
I would suggest to rename the **`files`** folder from the **`scripting`** folder to **`eitems`**.

![image](https://user-images.githubusercontent.com/32937653/142304446-82a93576-6647-4f79-8acf-fd1d81cee590.png)

Because of this change, many plugins use this same name for the folder, **`files`**, and with that it will replace files. An example of this is the **ServerAdvertisement3** plugin itself: https://github.com/ESK0/ServerAdvertisement3/tree/master/scripting

**Comment by ESK0** [comment]
Thanks for a suggestion. Source is not meant to be mixed with other plugins.
