### ISSUE TITLE
Automatic update through a working script?

### ISSUE THREAD

**Issue by crashzk** [ESK0/eItems#7]
Would it be possible to configure an automatic update of eItems? Whenever a new version is released, the server will already download directly from GitHub the files in the `data` folder, the complete plugin itself.

Asked because whenever an update comes out we need to send the new files. Anyway, would that be possible now? If not, are you thinking of implementing it?

**Comment by crashzk** [comment]
Any news on this feature? Any scripts we can use to update the files in the `data` folder ourselves whenever CSGO releases an update?

**Comment by ESK0** [comment]
Im not doing any CSGO anymore. eItems is updated automatically via a script

**Comment by crashzk** [comment]
> Im not doing any CSGO anymore. eItems is updated automatically via a script 

I understand, in relation to this script that you use to update, could you share it so that we can use it for the files in the folder `data`, **items_en** and etc.

**Comment by manicogaming** [comment]
The script hasn't added the new Anubis Collection so maybe there's something wrong with it.

**Comment by crashzk** [comment]
One more update on today's date _**(4/5/2023)**_ but the script has not updated.

https://www.counter-strike.net/news/updates

**Comment by mrc4tt** [comment]
New update today, but not been deployed or updated to eItems. ;(

**Comment by ESK0** [comment]
@NomisCZ 🧢

**Comment by dran1x** [comment]
> The script hasn't added the new Anubis Collection so maybe there's something wrong with it.

Yeah, about two weeks or so valve disabled their econ items schema endpoint.

**Comment by manicogaming** [comment]
> > The script hasn't added the new Anubis Collection so maybe there's something wrong with it.
> 
> Yeah, about two weeks or so valve disabled their econ items schema endpoint.

So what alternative so we have?

**Comment by dran1x** [comment]
> > > The script hasn't added the new Anubis Collection so maybe there's something wrong with it.
> 
> > 
> 
> > Yeah, about two weeks or so valve disabled their econ items schema endpoint.
> 
> 
> 
> So what alternative so we have?

I'm working on an alternative right now that doesn't require an api.

**Comment by crashzk** [comment]
@dran1x we are waiting for your alternative in this case. For now, eItems has been updated, I'll be testing it and I'll return anything here.

**Comment by crashzk** [comment]
Note, CSGO released some sticker fixes just now. I'll wait to see if the script automatically updates again.

**Comment by ESK0** [comment]
> Note, CSGO released some sticker fixes just now. I'll wait to see if the script automatically updates again.

https://github.com/ESK0/eItems/commit/5dd54ccc5197aa532bbfc2fd4fe2d4076cc701a4
